version: 2.1

description: |
  API token is from $REALMETHODS_API_TOKEN. This token is obtained from your online account under User Preferences.
  The source for this Orb is available at https://github.com/realmethods-public/orb.

commands:
  initialize:
    description: |
      Initialize the realmethods_cli environment
    parameters:
      api-token:
        description: "A user's API token for the realMethods CLI"
        type: string
        default: "${REALMETHODS_API_TOKEN}"
    steps:
      - checkout:
          path: "~/${CIRCLE_PROJECT_REPONAME}"
      - run:
          name: update npm
          command: 'sudo npm install -g npm@latest'    
      - run:
          name: install npm-run
          command: 'sudo npm install -g npm-run@latest'    
      - run:
          name: install realmethods CLI
          command: 'sudo npm install -g realmethods_cli'
      - run:
          name: list out working_directory
          command: 'sudo ls ~/${CIRCLE_PROJECT_REPONAME}'
      - run:
          name: initialize user for realmethods CLI 
          command: sudo npm-run realmethods_cli init << parameters.api-token >>

  generate_app:
    description: |
      Generate a complete application using the directives of user provided YAML file.
    parameters:
      generation-yaml-file:
        description: "YAML file containing the application generation directives"
        type: string
        default: "${GENERATION_YAML_FILE}"
    steps:
      - run:
          name: Generate the application
          command: realmethods_cli app_generate ~/${CIRCLE_PROJECT_REPONAME}/<< parameters.generation-yaml-file >>
jobs:
  appgen:
    description: |
      Check out code, install realMethods CLI, initialize with the user API token, and generate using the provided generation_yaml file
    docker:
      - image: circleci/node:8.12.0-jessie      
    steps:
      - initialize
      - generate_app
