version: 2.1

description: An orb with some simple ways to help you with your first build.

commands:
  circleci-env-highlights:
    steps:
    - run:
        command: |-
          echo "TRIGGERER: ${CIRCLE_USERNAME}"
          echo "BUILD_NUMBER: ${CIRCLE_BUILD_NUM}"
          echo "BUILD_URL: ${CIRCLE_BUILD_URL}"
          echo "BRANCH: ${CIRCLE_BRANCH}"
          echo "RUNNING JOB: ${CIRCLE_JOB}"
          echo "JOB PARALLELISM: ${CIRCLE_NODE_TOTAL}"
          echo "CIRCLE_REPOSITORY_URL: ${CIRCLE_REPOSITORY_URL}"
        name: Show some of the CircleCI runtime env vars

  hello-triggerer:
    parameters:
      to:
        default: ${CIRCLE_USERNAME}
        type: string
    steps:
    - run: echo "Hello << parameters.to >>"

  system-info:
    steps:
    - run:
        command: |-
          echo "uname:" $(uname -a)
          echo "arch: " $(arch)
        name: Show system information

executors:
  default:
    docker:
    - image: circleci/buildpack-deps:<< parameters.tag >>
    parameters:
      tag:
        default: curl-browsers
        type: string

jobs:
  hello-build:
    executor: default
    steps:
    - hello-triggerer
    - circleci-env-highlights
    - system-info