version: 2.1

description: |
  API token is from $REALMETHODS_API_TOKEN. This token is obtained from your online account under User Preferences.
  The source for this Orb is available at https://github.com/realmethods-public/orb

commands:
  initialize:
    description: |
      Initialize the realmethods_cli environment
    parameters:
      api-token:
        description: "A user's API token for the realMethods CLI"
        type: string
        default: "${REALMETHODS_API_TOKEN}"
    steps:
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'    
      - run:
          name: install rM CLI
          command: 'sudo npm install realmethods_cli'
      - run:
          name: initialize user for rM CLI 
          command: sudo realmethods_cli init << api-token >>

  generate_app:
    description: |
      Generate a complete application using the directives of user provided YAML file.
    parameters:
      generation-yaml-file:
        description: "YAML file containing the application generation directives"
        type: string
        default: "${GENERATION_YAML_FILE}"
    steps:
      - run:
          name: Generate the application
          command: realmethods_cli app_generate << parameters.generation-yaml-file >>
jobs:
  appgen:
    description: |
      Check out code, install realMethods CLI, initialize with the user API token, and generate using the provided generation_yaml file
    docker:
      - image: circleci/node:8.12.0-jessie      
    steps:
      - checkout
      - initialize
      - generate_app
