version: 2.1

orbs:
  realmethods: realmethods/appgen@2.0.0

jobs:
  generate-devops-project:
  
    docker:
      - image: 'circleci/node:latest'

    steps:
      - realmethods/initialize:
          api-token: DsJqTpYht3LcKb80 # YOUR_TOKEN_HERE : this CircleCI user token will work for all CircleCI usage, 
                                      # but you can replace it with your token as a registered user on platform.realmethods.com 

##################################################################
## Multiple app generations are included to give an example of
## usage for each supported technology stacks. Only include the 
## section(s) you need.
##
## Learn more about configuration files and settings at:
## https://realmethods.com/home/command-line-interface/ 
###################################################################

## Apollo GraphQL
##      - realmethods/generate_devops_project:
##          generation-yaml-file: "samples/yamls/project.as.code/apollo-project-as-code.yml"

## Angular7          
##      - realmethods/generate_devops_project:
##          generation-yaml-file: "samples/yamls/project.as.code/angular-project-as-code.yml"

## ASP.NET          
##      - realmethods/generate_devops_project:
##          generation-yaml-file: "samples/yamls/project.as.code/aspdotnet-project-as-code.yml"

## Django
      - realmethods/generate_devops_project:
          generation-yaml-file: "samples/yamls/project.as.code/django-project-as-code.yml"

## Spring Boot using MongoDB
##      - realmethods/generate_devops_project:
##          generation-yaml-file: "samples/yamls/project.as.code/springboot-mongodb-project-as-code.yml"

##           
## Spring Boot using MySQL          
##      - realmethods/generate_devops_project:
##          generation-yaml-file: "samples/yamls/project.as.code/springboot-rdbms-project-as-code.yml"

## Spring Boot using MongoDB
##      - realmethods/generate_devops_project:
##          generation-yaml-file: "samples/yamls/project.as.code/springboot-mongodb-project-as-code.yml"
           
## Spark Microweb using MySQL
##      - realmethods/generate_devops_project:
##          generation-yaml-file: "samples/yamls/project.as.code/sparkmicroweb-project-as-code.yml"

# Google Functions          
##      - realmethods/generate_devops_project:
##         generation-yaml-file: "samples/yamls/project.as.code/googlefunctions-project-as-code.yml"


## Struts2 using MySQL
##      - realmethods/generate_devops_project:
##          generation-yaml-file: "samples/yamls/project.as.code/struts-rdbms-project-as-code.yml"
  
          
#################################################################
# In order to deploy the generated Lambda functions, the key vars 
# (USER_AWS_ACCESSKEY and USER_AWS_SECRETKEY) are 
# read in as env vars for the current project. 
# Learn how to add these env vars at 
# https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-project 
#################################################################
            
## AWS Lambda using MySQL          
##      - realmethods/generate_devops_project:
##          generation-yaml-file: "samples/yamls/project.as.code/generate-lambdacore.yml"
           
## AWS Lambda using MongoDB
##      - realmethods/generate_devops_project:
##          generation-yaml-file: "samples/yamls/project.as.code/generate-lambdanosql.yml"
 
workflows:
  version: 2
  project-generations-workflow:
    jobs:
      - generate-devops-project
