version: 2.1

orbs:
  realmethods: dev-sandbox/realmethods@dev:0.0.3

jobs:
  generate-app:
    docker:
      - image: 'circleci/node:8.12.0-jessie'
    steps:
      - realmethods/initialize:
          api-token: "sny6iLHAH4SMJU1F"
      - realmethods/generate_app:
          generation-yaml-file: "samples/yamls/generate-springnosql.yml"
          git-params-file: "samples/git/test.git.yml"
          app-options-file: "samples/options/remote/SpringMongoDB.options.json"

workflows:
  version: 2
  what_to_do:
    jobs:
      - generate-app
  