version: 2.1

orbs:
  realmethods: realmethods/realmethods@dev:0.0.3

jobs:
  generate-app:
    docker:
      - image: 'circleci/node:8.12.0-jessie'
    steps:
      - realmethods/initialize:
          api-token: "sny6iLHAH4SMJU1F"
##################################################################
## Multiple app generations are included to give an example of
## usage for each supported technology stacks. Only include the 
## section(s) you need.
##
## Learn more about configuration files and settings at:
## https://www.realmethods.com/cli.html#config-files
###################################################################

## Django
      - realmethods/generate_app:
          generation-yaml-file: "samples/yamls/generate-django.yml"
          git-params-file: "samples/git/test.git.yml"
          app-options-file: "samples/options/remote/Django.options.json"
          model-identifier: "samples/models/reference_management.xmi"
          
## Angular7          
##      - realmethods/generate_app:
##          generation-yaml-file: "samples/yamls/generate-angular.yml"
##          git-params-file: "samples/git/test.git.yml"
##          app-options-file: "samples/options/remote/Angular7MongoDB.options.json"
##          model-identifier: "samples/models/reference_management.xmi"          

## ASP.NET          
##      - realmethods/generate_app:
##          generation-yaml-file: "samples/yamls/generate-aspdotnet.yml"
##          git-params-file: "samples/git/test.git.yml"
##          app-options-file: "samples/options/remote/ASPNETCore.options.json"
##          model-identifier: "samples/models/reference_management.xmi"
          
# Google Functions          
##      - realmethods/generate_app:
##          generation-yaml-file: "samples/yamls/generate-googlefunctions.yml"
##          git-params-file: "samples/git/test.git.yml"
##          app-options-file: "samples/options/remote/GoogleFunctions.options.json"
##          model-identifier: "samples/models/reference_management.xmi"
           
## AWS Lambda using MySQL          
##      - realmethods/generate_app:
##          generation-yaml-file: "samples/yamls/generate-lambdacore.yml"
##          git-params-file: "samples/git/test.git.yml"
##          app-options-file: "samples/options/remote/Lambda.options.json"
##          model-identifier: "samples/models/reference_management.xmi"
           
## AWS Lambda using MongoDB
##      - realmethods/generate_app:
##          generation-yaml-file: "samples/yamls/generate-lambdanosql.yml"
##          git-params-file: "samples/git/test.git.yml"
##          app-options-file: "samples/options/remote/LambdaNoSQL.options.json"
##          model-identifier: "samples/models/reference_management.xmi"
           
## Spring Boot using MySQL          
##      - realmethods/generate_app:
##          generation-yaml-file: "samples/yamls/generate-springcore.yml"
##          git-params-file: "samples/git/test.git.yml"
##          app-options-file: "samples/options/remote/SpringCore.options.json"
##          model-identifier: "samples/models/reference_management.xmi"
            
## Spring Boot using MongoDB
##      - realmethods/generate_app:
##          generation-yaml-file: "samples/yamls/generate-springnosql.yml"
##          git-params-file: "samples/git/test.git.yml"
##          app-options-file: "samples/options/remote/SpringMongoDB.options.json"
##          model-identifier: "samples/models/reference_management.xmi"
 
## Struts2 using MySQL
##      - realmethods/generate_app:
##          generation-yaml-file: "samples/yamls/generate-struts2.yml"
##          git-params-file: "samples/git/test.git.yml"
##          app-options-file: "samples/options/remote/Struts2.options.json"
##          model-identifier: "samples/models/reference_management.xmi"
 
## Spark Microweb using MySQL
##      - realmethods/generate_app:
##          generation-yaml-file: "samples/yamls/generate-sparkmicroweb.yml"
##          git-params-file: "samples/git/test.git.yml"
##          app-options-file: "samples/options/remote/SparkMicroWeb.options.json"
##          model-identifier: "samples/models/reference_management.xmi"
 
workflows:
  version: 2
  app-gen-workflow:
    jobs:
      - generate-app
       